/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCandidatoRouteImport } from './routes/admin/candidato'
import { Route as AdminColaboradorRouteImport } from './routes/admin/colaborador'
import { Route as AdminInteressadosRouteImport } from './routes/admin/interessados'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as ApoioColaboradorIdRouteImport } from './routes/apoio/$colaboradorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatoRoute = AdminCandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColaboradorRoute = AdminColaboradorRouteImport.update({
  id: '/colaborador',
  path: '/colaborador',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInteressadosRoute = AdminInteressadosRouteImport.update({
  id: '/interessados',
  path: '/interessados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const ApoioColaboradorIdRoute = ApoioColaboradorIdRouteImport.update({
  id: '/apoio/$colaboradorId',
  path: '/apoio/$colaboradorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/candidato': typeof AdminCandidatoRoute
  '/admin/colaborador': typeof AdminColaboradorRoute
  '/admin/interessados': typeof AdminInteressadosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/apoio/$colaboradorId': typeof ApoioColaboradorIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/candidato': typeof AdminCandidatoRoute
  '/admin/colaborador': typeof AdminColaboradorRoute
  '/admin/interessados': typeof AdminInteressadosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/apoio/$colaboradorId': typeof ApoioColaboradorIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/candidato': typeof AdminCandidatoRoute
  '/admin/colaborador': typeof AdminColaboradorRoute
  '/admin/interessados': typeof AdminInteressadosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/apoio/$colaboradorId': typeof ApoioColaboradorIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/admin/candidato'
    | '/admin/colaborador'
    | '/admin/interessados'
    | '/admin/usuarios'
    | '/apoio/$colaboradorId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/admin/candidato'
    | '/admin/colaborador'
    | '/admin/interessados'
    | '/admin/usuarios'
    | '/apoio/$colaboradorId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/admin/candidato'
    | '/admin/colaborador'
    | '/admin/interessados'
    | '/admin/usuarios'
    | '/apoio/$colaboradorId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ApoioColaboradorIdRoute: typeof ApoioColaboradorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidato': {
      id: '/admin/candidato'
      path: '/candidato'
      fullPath: '/admin/candidato'
      preLoaderRoute: typeof AdminCandidatoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colaborador': {
      id: '/admin/colaborador'
      path: '/colaborador'
      fullPath: '/admin/colaborador'
      preLoaderRoute: typeof AdminColaboradorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interessados': {
      id: '/admin/interessados'
      path: '/interessados'
      fullPath: '/admin/interessados'
      preLoaderRoute: typeof AdminInteressadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apoio/$colaboradorId': {
      id: '/apoio/$colaboradorId'
      path: '/apoio/$colaboradorId'
      fullPath: '/apoio/$colaboradorId'
      preLoaderRoute: typeof ApoioColaboradorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCandidatoRoute: typeof AdminCandidatoRoute
  AdminColaboradorRoute: typeof AdminColaboradorRoute
  AdminInteressadosRoute: typeof AdminInteressadosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCandidatoRoute: AdminCandidatoRoute,
  AdminColaboradorRoute: AdminColaboradorRoute,
  AdminInteressadosRoute: AdminInteressadosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ApoioColaboradorIdRoute: ApoioColaboradorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
